Missing declaration for windows
Fixes:

```

../../../../ext/teek/tkwin.c: In function 'interp_native_window_handle':
../../../../ext/teek/tkwin.c:205:21: error: implicit declaration of function 'Tk_GetHWND' [-Wimplicit-function-declaration]
  205 |         HWND hwnd = Tk_GetHWND(drawable);
      |                     ^~~~~~~~~~
../../../../ext/teek/tkwin.c:205:21: error: initialization of 'HWND' {aka 'struct HWND__ *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
make: *** [Makefile:251: tkwin.o] Error 1
```